workflows:
  react-native-ios:
    name: Aquarium Fish Quiz
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: AquariumAppStoreApiKeyName
    triggering:
      events:
        - push
    environment:
      vars:
        BUNDLE_ID: 'com.aquarium.fishquiz'
        XCODE_WORKSPACE: 'AquariumFishQuiz.xcworkspace'
        XCODE_SCHEME: 'AquariumFishQuiz'
        APP_STORE_APPLE_ID: 6590616728
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          gem install cocoapods
          pod install
      - name: Set up provisioning profile settings on  Xcode project
        script: xcode-project use-profiles
      - name: Build iOS unsigned
        script: |
          xcodebuild build -project "AquariumFishQuiz.xcodeproj"\
          -scheme "AquariumFishQuiz"
