workflows:
  react-native-ios:
    name: Aquarium Fish Quiz
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: AquariumAppStoreApiKeyName
    triggering:
      events:
        - push
    environment:
      vars:
        BUNDLE_ID: 'com.aquarium.fishquiz'
        XCODE_WORKSPACE: 'AquariumFishQuiz.xcworkspace'
        XCODE_SCHEME: 'AquariumFishQuiz'
        APP_STORE_APPLE_ID: 6590616728
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install node modules
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: | 
          cd ios && pod install
      - name: Set up provisioning profile settings on  Xcode project
        script: |
          cd ios
          xcode-project use-profiles
      - name: Build IPA for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/AquariumFishQuiz.xcworkspace" \
            --scheme "AquariumFishQuiz"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM