workflows:
  react-native-ios:
    name: Aquarium Fish Quiz
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: AquariumAppStoreApiKeyName
    triggering:
      events:
        - push
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.aquarium.fishquiz
      vars:
        BUNDLE_ID: 'com.aquarium.fishquiz'
        XCODE_WORKSPACE: 'AquariumFishQuiz.xcworkspace'
        XCODE_SCHEME: 'AquariumFishQuiz'
        APP_STORE_APPLE_ID: 6590616728
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install node modules
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          gem install cocoapods
          pod install
      - name: Set up provisioning profile settings on  Xcode project
        script: |
          cd ios
          xcode-project use-profiles
      - name: Build IPA for distribution
        script: |
          xcode-project build-ipa \
          --workspace "$CM_BUILD_DIR/ios/AquariumFishQuiz.xcworkspace" \
          --scheme "$XCODE_SCHEME"
    artifacts:
        - build/ios/ipa/*.ipa
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
