workflows:
  react-native-ios:
    name: Aquarium Fish Quiz
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: AquariumSigninCertificate
    triggering:
      events:
        - push
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.aquarium.fishquiz
      vars:
        BUNDLE_ID: "com.aquarium.fishquiz"
        XCODE_WORKSPACE: "AquariumFishQuiz.xcworkspace"
        XCODE_SCHEME: "AquariumFishQuiz"
        APP_STORE_APPLE_ID: 6590616728
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: | 
          pod install
      - name: Set up provisioning profile settings on  Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
